# Generated by Django 4.2.14 on 2024-08-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
                ('car_version', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
            ],
        ),
    ]
